export const headCells = [
  {id: 'Round',
   numeric: true,
   disablePadding: false,
   label: '#',
  },
  {id: 'ContestName',
   numeric: false,
   disablePadding: true,
   label: 'Contest Name',
  },
  {id: 'Performance',
   numeric: true,
   disablePadding: false,
   label: 'Estimated Performance',
  },
  {id: 'NewRating',
   numeric: true,
   disablePadding: false,
   label: 'New Rating',
  },
  {id: 'Diff',
   numeric: true,
   disablePadding: false,
   label: 'Diff',
  },
];
